export const DELETE_WORKFLOW = "DELETE_WORKFLOW";
export const UPDATE_WORKFLOW_STATE = "UPDATE_WORKFLOW_STATE";
export const ADD_WORKFLOW = "ADD_WORKFLOW";
export const UPDATE_WORKFLOW = "UPDATE_WORKFLOW";
export const SET_WORKFLOWS = "SET_WORKFLOWS";
export const SET_GETTING_WORKFLOWS = "GETTING_WORKFLOWS";
export const SET_SAVING_WORKFLOW = "SET_SAVING_WORKFLOW";