export const DELETE_WORKFLOW = "DELETE_WORKFLOW";
export const UPDATE_WORKFLOW_STATE = "UPDATE_WORKFLOW_STATE";
export const ADD_WORKFLOW = "ADD_WORKFLOW";
export const UPDATE_WORKFLOW = "UPDATE_WORKFLOW";